const express=require("express"),helmet=require("helmet"),fs=require("fs"),path=require("path"),crypto=require("crypto");
let pdfParse=null,mammoth=null,XLSX=null;
try{pdfParse=require("pdf-parse")}catch(e){}
try{mammoth=require("mammoth")}catch(e){}
try{XLSX=require("xlsx")}catch(e){}
const app=express(),PORT=process.env.PORT||10000;
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:"35mb"}));
app.use(express.static(path.join(__dirname,"public")));
const USERS=path.join(__dirname,"data","users.json"),SETTINGS=path.join(__dirname,"data","settings.json"),PROMPTS=path.join(__dirname,"data","prompts.json"),KNOWLEDGE=path.join(__dirname,"data","knowledge.md"),EXPORTS=path.join(__dirname,"exports");
fs.mkdirSync(EXPORTS,{recursive:true});
const TOKENS=new Map();
const KEYS=["chat","pesquisa","tecnico","atendimento","programador","marketing","usuarios","configuracoes","imagem","editarImagem","video","documentos","sites","codigo","arquivos"];
const DEF={
 admin:Object.fromEntries(KEYS.map(k=>[k,true])),
 atendente:{chat:true,pesquisa:true,tecnico:false,atendimento:true,programador:false,marketing:true,usuarios:false,configuracoes:false,imagem:false,editarImagem:false,video:false,documentos:true,sites:false,codigo:false,arquivos:true},
 tecnico:{chat:true,pesquisa:true,tecnico:true,atendimento:false,programador:false,marketing:false,usuarios:false,configuracoes:false,imagem:false,editarImagem:false,video:false,documentos:true,sites:false,codigo:false,arquivos:true},
 programador:{chat:true,pesquisa:true,tecnico:false,atendimento:false,programador:true,marketing:false,usuarios:false,configuracoes:false,imagem:false,editarImagem:false,video:false,documentos:true,sites:true,codigo:true,arquivos:true},
 marketing:{chat:true,pesquisa:true,tecnico:false,atendimento:true,programador:false,marketing:true,usuarios:false,configuracoes:false,imagem:true,editarImagem:true,video:true,documentos:true,sites:false,codigo:false,arquivos:true}
};
function rj(f,d){try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,"utf8")):d}catch{return d}}
function wj(f,d){fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(d,null,2),"utf8")}
function rt(f){try{return fs.existsSync(f)?fs.readFileSync(f,"utf8"):""}catch{return""}}
function validMode(m){return KEYS.includes(m)||["rapido"].includes(m)}
function settings(){let s=rj(SETTINGS,{appName:"OLITECH I.A V3.1",subtitle:"Pesquisa, sistemas, sites, imagens, vídeos, documentos e atendimento.",logoType:"url",logoText:"IA",logoUrl:"/assets/olitech-ia-logo.png",logoData:"",defaultMode:"pesquisa"}); if(!validMode(s.defaultMode)||s.defaultMode==="imagem")s.defaultMode="pesquisa"; return s}
function normP(role,p={}){if(role==="admin")return {...DEF.admin};let b=DEF[role]||DEF.atendente,o={};KEYS.forEach(k=>o[k]=!!(p[k]??b[k]));return o}
function norm(u){let role=DEF[u.role]?u.role:"atendente";return{id:u.id||"u_"+crypto.randomBytes(8).toString("hex"),username:String(u.username||"").trim(),password:String(u.password||""),name:String(u.name||u.username||"Usuário").trim(),role,active:u.active!==false,permissions:normP(role,u.permissions||{})}}
function clean(u){u=norm(u);return{id:u.id,username:u.username,name:u.name,role:u.role,active:u.active,permissions:u.permissions}}
function users(){let us=rj(USERS,[]);if(!us.some(u=>u.username==="olitech"))us.unshift({id:"admin_olitech",username:"olitech",password:"051309",name:"Olitech Admin",role:"admin",active:true,permissions:DEF.admin});us=us.map(norm);wj(USERS,us);return us}
function token(req){let a=req.headers.authorization||"";return a.startsWith("Bearer ")?a.slice(7):""}
function user(req){let t=token(req),s=TOKENS.get(t);if(!s||Date.now()>s.exp)return null;let u=users().find(x=>x.id===s.uid&&x.active);if(!u)return null;s.exp=Date.now()+7*864e5;TOKENS.set(t,s);return clean(u)}
function auth(req,res,next){let u=user(req);if(!u)return res.status(401).json({error:"Não autenticado. Faça login novamente."});req.user=u;next()}
function has(u,p){return u&&(u.role==="admin"||u.permissions?.[p])}
function perm(p){return(req,res,next)=>has(req.user,p)?next():res.status(403).json({error:"Sem permissão: "+p})}
function safe(n,ext){return String(n||"arquivo").replace(/[^\w\-]+/g,"_").slice(0,60)+(ext||"")}

app.get("/api/health",(req,res)=>res.json({ok:true,version:"v3.1-corrigida"}));
app.post("/api/login",(req,res)=>{let{username,password}=req.body||{},u=users().find(x=>x.username===username&&x.password===password&&x.active);if(!u)return res.status(401).json({error:"Usuário ou senha inválidos"});let t=crypto.randomBytes(32).toString("hex");TOKENS.set(t,{uid:u.id,exp:Date.now()+7*864e5});res.json({ok:true,token:t,user:clean(u),settings:settings()})});
app.post("/api/logout",auth,(req,res)=>{TOKENS.delete(token(req));res.json({ok:true})});
app.get("/api/me",(req,res)=>res.json({user:user(req),settings:settings()}));

app.get("/api/users",auth,perm("usuarios"),(req,res)=>res.json({users:users().map(clean),permissionKeys:KEYS,roleDefaults:DEF}));
app.post("/api/users",auth,perm("usuarios"),(req,res)=>{let b=req.body||{};if(!b.username||!b.password||!b.name||!b.role)return res.status(400).json({error:"Preencha nome, login, senha e perfil."});let us=users();if(us.some(u=>u.username.toLowerCase()===String(b.username).toLowerCase()))return res.status(400).json({error:"Login já existe."});us.push(norm({id:"u_"+crypto.randomBytes(8).toString("hex"),...b}));wj(USERS,us);res.json({ok:true,users:users().map(clean)})});
app.put("/api/users/:id",auth,perm("usuarios"),(req,res)=>{let us=users(),i=us.findIndex(u=>u.id===req.params.id),b=req.body||{};if(i<0)return res.status(404).json({error:"Usuário não encontrado."});if(b.username&&us.some(u=>u.id!==req.params.id&&u.username.toLowerCase()===String(b.username).toLowerCase()))return res.status(400).json({error:"Login já existe."});["username","name","role"].forEach(k=>{if(b[k])us[i][k]=b[k]});if(typeof b.active==="boolean")us[i].active=b.active;if(b.password)us[i].password=b.password;us[i].permissions=normP(us[i].role,b.permissions||us[i].permissions);us[i]=norm(us[i]);wj(USERS,us);res.json({ok:true,users:users().map(clean)})});
app.delete("/api/users/:id",auth,perm("usuarios"),(req,res)=>{if(req.user.id===req.params.id)return res.status(400).json({error:"Não exclua o próprio usuário."});wj(USERS,users().filter(u=>u.id!==req.params.id));res.json({ok:true,users:users().map(clean)})});

app.get("/api/settings",auth,(req,res)=>res.json({settings:settings()}));
app.put("/api/settings",auth,perm("configuracoes"),(req,res)=>{let c=settings(),b=req.body||{},mode=String((b.defaultMode??c.defaultMode??"pesquisa"));if(!validMode(mode)||mode==="imagem")mode="pesquisa";let s={appName:String(b.appName??c.appName).slice(0,80),subtitle:String(b.subtitle??c.subtitle).slice(0,180),logoType:["text","url","local"].includes(b.logoType)?b.logoType:c.logoType,logoText:String(b.logoText??c.logoText).slice(0,10),logoUrl:String(b.logoUrl??c.logoUrl).slice(0,600),logoData:String(b.logoData??c.logoData).slice(0,8000000),defaultMode:mode};wj(SETTINGS,s);res.json({ok:true,settings:s})});

app.post("/api/chat",auth,perm("chat"),async(req,res)=>{try{let{message,mode}=req.body||{};if(!message)return res.status(400).json({error:"Mensagem vazia"});mode=mode||settings().defaultMode||"pesquisa";if(!validMode(mode))mode="pesquisa";if(mode!=="rapido"&&!has(req.user,mode))return res.status(403).json({error:"Sem permissão para "+mode});let search="",err="",need=mode==="pesquisa"||/pesquis|clima|chuva|chover|tempo|preço|valor|hoje|atual|site|sistema|imagem|código|codigo|video|documento/i.test(message);if(need&&has(req.user,"pesquisa")){let r=await webSearch(String(message));search=r.text;err=r.error}let p=rj(PROMPTS,{}),k=rt(KNOWLEDGE),sys=`${p.base||""}\n${p[mode]||""}\nBase:${k}\nPesquisa:${search||"nenhuma"}\nErro:${err||"nenhum"}`;let answer=await callAI(sys,String(message),{searchText:search,searchError:err});res.json({answer,usedSearch:!!search,searchError:err})}catch(e){res.json({answer:"Erro técnico tratado: "+e.message+"\n\nA OLITECH I.A continua ativa. Verifique se GROQ_API_KEY está configurada no Render.",usedSearch:false,searchError:e.message})}});

app.post("/api/tools/analyze-file",auth,perm("arquivos"),async(req,res)=>{try{let{name,mime,data}=req.body||{};if(!data)return res.status(400).json({error:"Arquivo vazio."});let buf=Buffer.from(String(data).split(",").pop(),"base64"),text="",lower=String(name||"").toLowerCase();if(lower.match(/\.(png|jpg|jpeg|webp|gif)$/)){return res.json({ok:true,name,mime,text:`Imagem anexada: ${name}. A leitura visual real será adicionada com API de visão. Use o modo Editar imagem ou Imagem para criar instruções/prompt.`})}if(lower.endsWith(".pdf")){if(!pdfParse)return res.json({ok:false,error:"Leitor PDF não instalado. Rode npm install novamente no Render."});let p=await pdfParse(buf);text=p.text||""}else if(lower.endsWith(".docx")){if(!mammoth)return res.json({ok:false,error:"Leitor DOCX não instalado. Rode npm install novamente no Render."});let r=await mammoth.extractRawText({buffer:buf});text=r.value||""}else if(lower.endsWith(".xlsx")||lower.endsWith(".xls")){if(!XLSX)return res.json({ok:false,error:"Leitor XLSX não instalado. Rode npm install novamente no Render."});let wb=XLSX.read(buf,{type:"buffer"});text=wb.SheetNames.map(s=>"# "+s+"\n"+XLSX.utils.sheet_to_csv(wb.Sheets[s])).join("\n\n")}else{text=buf.toString("utf8").replace(/[^\x09\x0A\x0D\x20-\x7EÀ-ÿ]/g," ").replace(/\s{3,}/g," ")}res.json({ok:true,name,mime,text:text.slice(0,50000)})}catch(e){res.status(200).json({ok:false,error:e.message})}});

app.post("/api/tools/image",auth,perm("imagem"),async(req,res)=>{try{let{prompt,size}=req.body||{};if(!prompt)return res.status(400).json({error:"Digite o prompt da imagem."});if(process.env.OPENAI_API_KEY){let r=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:"Bearer "+process.env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-1",prompt,size:size||"1024x1024"}),signal:AbortSignal.timeout(90000)});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||"Erro ao gerar imagem");return res.json({ok:true,type:"image",data:d})}return res.json({ok:true,type:"prompt",message:"API de imagem não configurada. Configure OPENAI_API_KEY no Render. Prompt otimizado:",prompt:await optimizePrompt(prompt)})}catch(e){res.status(200).json({ok:false,error:e.message})}});

app.post("/api/tools/video",auth,perm("video"),(req,res)=>{let{idea}=req.body||{};res.json({ok:true,content:`Roteiro de vídeo/reels OLITECH\nTema: ${idea}\nCena 1: abertura com logo.\nCena 2: mostrar problema.\nCena 3: mostrar solução técnica.\nCena 4: prova visual.\nCena 5: chamada para WhatsApp.\nPrompt: vídeo comercial futurista azul e laranja, assistência técnica, 15 segundos, transições rápidas.`,message:"Vídeo real depende de API externa como Runway, Kling, Pika, Luma ou Replicate."})});
app.post("/api/tools/site",auth,perm("sites"),async(req,res)=>{let{description}=req.body||{};let prompt=`Crie uma página HTML completa, responsiva, moderna e profissional para: ${description}. Entregue em um único arquivo com HTML, CSS e JS internos.`;let answer=await callAI("Você é programador web especialista.",prompt,{});let file=safe("site_olitech",".html");fs.writeFileSync(path.join(EXPORTS,file),answer,"utf8");res.json({ok:true,filename:file,url:"/exports/"+file,content:answer})});
app.use("/exports",express.static(EXPORTS));

async function webSearch(q){if(/clima|chuva|chover|tempo/i.test(q)){try{let city=q.replace(/vai chover|chover|chuva|hoje|clima|tempo|\?/gi," ").trim()||"Ibitinga SP",rr=await fetch("https://wttr.in/"+encodeURIComponent(city)+"?format=j1",{signal:AbortSignal.timeout(10000)});if(rr.ok){let d=await rr.json(),c=d.current_condition?.[0]||{},t=d.weather?.[0]||{};return{text:`Fonte wttr.in ${city}: ${c.temp_C||"?"}°C, máxima ${t.maxtempC||"?"}°C, mínima ${t.mintempC||"?"}°C.`,error:""}}}catch(e){return{text:"",error:e.message}}}try{let r=await fetch("https://api.duckduckgo.com/?q="+encodeURIComponent(q)+"&format=json&no_html=1&skip_disambig=1",{signal:AbortSignal.timeout(9000)});if(r.ok){let d=await r.json(),out=[];if(d.AbstractText)out.push(d.AbstractText+"\nFonte: "+(d.AbstractURL||"DuckDuckGo"));(d.RelatedTopics||[]).slice(0,5).forEach(x=>{if(x.Text)out.push(x.Text+"\nFonte: "+(x.FirstURL||""))});if(out.length)return{text:out.join("\n\n"),error:""}}}catch(e){return{text:"",error:e.message}}return{text:"",error:"Pesquisa externa sem resultado útil."}}
async function optimizePrompt(p){return"Imagem profissional futurista, alta qualidade, marca OLITECH, cores azul e laranja, tecnologia, assistência técnica, detalhes nítidos, composição comercial. "+p}
async function callAI(sys,msg,meta){if(process.env.AI_PROVIDER==="groq"&&process.env.GROQ_API_KEY){try{let r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+process.env.GROQ_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.GROQ_MODEL||"llama-3.1-8b-instant",messages:[{role:"system",content:sys},{role:"user",content:msg}],temperature:.35}),signal:AbortSignal.timeout(30000)});let d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error?.message||"Erro Groq");return d.choices?.[0]?.message?.content||"Sem resposta."}catch(e){return `Não consegui acessar a API Groq agora (${e.message}).\n\nResposta local:\n${localAnswer(msg,meta)}`}}return localAnswer(msg,meta)}
function localAnswer(msg,meta){return`OLITECH I.A V3.1 - modo local\n\nRecebi:\n${msg}\n\n${meta?.searchText?("Pesquisa externa:\n"+meta.searchText):"Para respostas completas de IA, configure GROQ_API_KEY no Render."}\n\nPosso ajudar com: sistemas, sites, códigos, documentos, prompts de imagem, roteiros de vídeo e atendimento.`}
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log("OLITECH I.A V3.1 corrigida online porta "+PORT));
